language: java
sudo: true
before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "esgi-4-al"

jobs:
  include:
    - stage: test
      name: "Test"
      script:
        - ./mvnw clean test -Ptest
    - stage: coverage
      name: "Coverage..."
      script:
        - ./mvnw clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=UgoPerniceni_cocotton-backend -Dsonar.login=${SONAR_TOKEN}
    - stage: build
      name: "Build..."
      script:
        - ./mvnw clean package -DskipTests
    - stage: deploy
      name: "Deploy..."
      provider: gae
      keyfile: ./cocotton-api-7cad61f97f44.json
      project: "cocotton-api"
      script:
        - ./mvnw appengine:deploy -P cloud-gcp
