language: java
sudo: true
before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "esgi-4-al"

jobs:
  include:
    - stage: test
      name: "Test"
      script:
        - ./mvnw clean test -Ptest
    - stage: coverage
      name: "Coverage..."
      script:
        - ./mvnw clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=UgoPerniceni_cocotton-backend -Dsonar.login=${SONAR_TOKEN}
    - stage: build
      name: "Build..."
      script:
        - ./mvnw clean package -DskipTests -P prod
    - stage: deploy
      name: "Deploy..."
      provider: elasticbeanstalk
      access_key_id:
        secure: "Encrypted AKIAUONV2A6OXDMO2JCV"
      secret_access_key:
        secure: "Encrypted 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"
      region: "us-east-2"
      app: "cocotton"
      env: "Cocotton-env"
      zip_file: target/cocotton-backend-0.0.1-SNAPSHOT.jar
      bucket_name: "elasticbeanstalk-us-east-2-305860839325"
